### PR TITLE
Features/119 remove r&w log table

### PR DESCRIPTION
**Pull request by richardli5945**
Created a new table "pv_user_log" to avoid low performance when patient user login.

### CODE REVIEW

**Comment by paulchenery** [comment]
Richard,

What is stopping the UserLog table from being composed of a userId and lastDataLoadDate?

**Comment by richardli5945** [comment]
Hi Paul,

When importer job import the patient in to DB, meanwhileit insert into the log table with action value is "patient data load", it also insert/update the record in  (pv_user_log) UserLog table with lastdatadate, so when patient login, it will query the UserLog(pv_user_log) table instead of log table. Other way, when patient is added in PV, it also insert/update a record in to UserLog.

**Comment by richardli5945** [comment]
Hi Paul,

Ok, I will remove the script into common area.

**Comment by richardli5945** [comment]
Hi Paul, 

Because in old code, it use the nhsno to query the log table. And when importer running, the patient  might not be r already existed in DB, log table store the user with theirs username,so that may be the dirty data in UserLog table when username in PV not same with importer. The unitcode is used in login to show where the patient date load from.

**Comment by paulchenery** [comment]
Hi Richard,

Thanks, that is fine.  Can you add this information as a comment to the code?

**Comment by richardli5945** [comment]
Hi Paul,

Ok, no problem.

**Pull request merged**
